### PR TITLE
add_vehicle_crud

### PR DESCRIPTION
**Pull request by Sebastian-Kujawa**

### CODE REVIEW

**Review by Pwlbkw — APPROVED** [review]

**Review by piotr-rapinski — CHANGES_REQUESTED** [review]
Two times .models import

**Review by TomekBr — APPROVED** [review]
Git !

**Review by Sebastian-Kujawa — COMMENTED** [review]
deleted duplicated .models

**Review by piotr-rapinski — APPROVED** [review]
now very good !

**Pull request merged**
